### ISSUE TITLE
Layout issue in main view

### ISSUE THREAD

**Issue by KHellkvist** [terkelg/ramme#156]
I can't see the things at the very top of the feed/profile I'm watching. 
And everything seems to be shifted to the right.
In both images I'm scrolled to the top.
Running on MacOS Sierra 10.12.5

Main feed:
![ramme-feed](https://user-images.githubusercontent.com/4183013/27381835-a097cff2-5684-11e7-9bc6-43975b35f071.png)

Profile:
![ramme-profile](https://user-images.githubusercontent.com/4183013/27381828-9ce41a46-5684-11e7-9c15-8a15b1a6b69f.png)

**Comment by bil-elmoussaoui** [comment]
Already fixed on master. please use the search functionality next time.

**Comment by KHellkvist** [comment]
Cheers!
Might wan't to not close the issue until fixed in release for discoverability. Or have reasonable naming "rules" of PR's so that one can find the fix there. 

Anyhow, sweet product! Nice that it is open source, maybe some contribution guidelines could help so you don't have to waste time on duplicate issues and the such!

**Comment by damenleeturks** [comment]
Agree with @KHellkvist. It's still showing this for me (understandably), but I had to dig (a bit) to find this issue.
