### ISSUE TITLE
Can't run on Linux

### ISSUE THREAD

**Issue by alpvonkri** [terkelg/ramme#82]
Can't run version 3.0.0 on openSUSE Linux.
Always get this error and app freezes, need to be forcekilled.
![screenshot_20170115_202621](https://cloud.githubusercontent.com/assets/104341/21969123/20678e06-db61-11e6-9635-f835a0a36d71.png)

**Comment by terkelg** [comment]
Thanks for reporting @alpvonkri. I'll have a look at it.

**Comment by terkelg** [comment]
Can you check the new version?

**Comment by YFoundIt** [comment]
i check it on mint 
it has same error

**Comment by anatolinicolae** [comment]
This issue has been solved now and will be available in the next release.

**Comment by alpvonkri** [comment]
Still the same in 3.0.1.

**Comment by terkelg** [comment]
Thanks for the feedback, and you're right it's still not working. However, @anatolinicolae fixed it and it will be a part of v3.0.2.

**Comment by alpvonkri** [comment]
Error fixed in 3.0.2., app works.
But now it doesn't show a system tray icon, so if closing the main window, app keeps running in background, so it needs to be force killed to close it.

**Comment by anatolinicolae** [comment]
I had this issue as well but didn't have time to dive into it. Will check by tomorrow and update you guys.

**Comment by anatolinicolae** [comment]
Can you guys tell me which Linux distributions and window managers you use so I can try something that works on your combos.

Both my Mint and Debian do not show any tray icon. Mint allows to minimize it to the task bar but nothing in the tray so far.

The force kill may be needed mainly because close button doesn't close the app but only hides it (then you can go check the tray and quit from there, if you see the tray icon).

**Comment by alpvonkri** [comment]
openSUSE Leap 42.2
KDE
RPM based installations.

**Comment by truckerboy** [comment]
Ubuntu 16.04 64 bit running gnome-shell (with libappindicator1 installed), same issue. Tray icon not visible but if I right click on where the tray icon is "supposed to be located", I get toggle/quit etc options when I right click. This is a regression from version 2.3.0 where it was working correctly.

**Comment by terkelg** [comment]
@anatolinicolae are you looking into this?

**Comment by anatolinicolae** [comment]
Sure thing, just have to check the different OS setups. Will update you guys ASAP.

**Comment by alpvonkri** [comment]
Update.
Still no icon in 3.0.3.

**Comment by bil-elmoussaoui** [comment]
Fixed on master, if your tray icons doesn't show up there's an open issue for that

**Comment by alpvonkri** [comment]
This Issue was always about the tray icon, and the fact that If you close Ramme main window you will need to kill the app as there is no icon.
Issue still present in version 3.2.0
Using: Plasma 5.9.95, Frameworks 5.34.0, QT 5.7.1

**Comment by truckerboy** [comment]
Just to be clear, tray icon is still not visible on Gnome tray but if I right click on the approximate location where the icon is "supposed to be located" (you have to do some guesswork where it could be on the Gnome tray), I get toggle/quit etc options. The issue has been a regression since version 2.3.0 (last version where the tray icon was visible) and has stayed that way through the current release (3.2.0). I am on Ubuntu 16.10 64 bit running Gnome 3.20.4. Please re-open the issue.

**Comment by bil-elmoussaoui** [comment]
It's not the same issue @truckerboy. The issue here is that the app doesn't run at all, there's an open issue for invisible tray icons. 
The invisible tray icon is an issue on electron, the old version 2.3.0 works just fine because Ramme used to use an old version of Electron and now we are using the latest version of it;
i'm aware of that, and i'm going to do my best to fix it

**Comment by truckerboy** [comment]
agreed, but all comments on this thread since 17-Jan-2017 have been about the missing tray icon. Might make sense to move comments to a new thread or merge if it already exists.

**Comment by bil-elmoussaoui** [comment]
Well, comments != issue. if you read the error message on the screenshot, you will see that there was a missing image. 
Anyway;, I will check with other electron apps and older versions of electron and figure out a solution that will make everyone satisfied!
